import { image_url } from "@/helper/Utilities";
import GameHeroVisual from "@/my_components/_Services/InnerPages/sections/GameHeroVisual";

// Config-driven content for the 10 non-Mobile, non-Cybersecurity service
// pages — each entry feeds my_components/_Services/InnerPages/ServicePageTemplate.js.
// `outcomeProjectIds` deliberately stays empty for services with no real
// shipped project behind them (Product Design, AI, 2D Animation, 2D Art) —
// the "Proof, not promises" section simply doesn't render rather than
// fabricating a case study that doesn't exist.

const tile = (src, alt) => ({ src: image_url(src, true), alt });

export const SERVICE_PAGES = {
  "web-development": {
    accent: "47 87 239",
    titleAccent: "Web App",
    titleRest: "Development Services",
    heroDesc:
      "Unleash the full potential of your business with our team of seasoned expert developers, crafting reliable, user-friendly web applications. Our solutions are designed to deliver flawless performance and an effortless experience — ensuring your users stay engaged, no matter their platform.",
    heroMode: "collage",
    tileShape: "browser",
    heroLayout: "1",
    heroTiles: [
      tile("/app_images/projects/digistate/website/homepage.png", "Digistate web platform"),
      tile("/app_images/projects/flatshare/homepage.png", "Flatshare web platform"),
      tile("/app_images/projects/geoplox/dashboard.png", "Geoplox web dashboard"),
      tile("/app_images/projects/xabi/wallet.png", "Xabi web platform"),
    ],
    whyImage: image_url("/app_images/services/service_art/web-development.webp", true),
    whyImageAlt: "Instrument diagram of responsive breakpoint frames, plotted for SmartTech's web development practice",
    faqImage: image_url("/app_images/services/service_art/web-development.webp", true),
    faqImageAlt: "Instrument diagram of responsive breakpoint frames, plotted for SmartTech's web development practice",
    countersTitle: "Why our clients love us",
    countersDesc: "For over 15 years, SmartTech has been the trusted partner of global brands, delivering exceptional web applications through our competent team.",
    allInOneTitle: "Comprehensive web development services",
    servicesKey: "web_dev_services",
    processDesc: "Our web development process is driven by an unwavering commitment to precision and care, ensuring each project is executed flawlessly.",
    procedureKey: "web_dev_service_procedure",
    whyTitle: "Why we are your ideal Web Development partner",
    whyDesc: "With over 15 years of expertise and a track record of hundreds of successful projects, SmartTech is the go-to partner for global brands seeking top-tier web applications.",
    whyPoints: [
      "A team of certified and skilled web developers",
      "Proficiency crafting secure and high-performance apps",
      "Robust security measures to protect data and transactions",
      "Scalable architecture designed for high traffic and growth",
      "Cutting-edge technology for future-proof digital products",
      "Seamless integration with APIs and enterprise systems",
      "Long-term support and continuous optimization for sustained success",
    ],
    outcomesTitle: "Web apps we've shipped and scaled",
    outcomesDesc: "A look inside real web platforms our team designed, engineered, and shipped for real businesses.",
    outcomeProjectIds: [6, 8, 11, 7],
    outcomeHighlights: {
      6: "SmartTech built a social flatmate-matching web platform with real-time messaging, listing filters, and location-based search built for speed and trust.",
      8: "SmartTech built a real-estate data platform that turns fragmented property data into a single trusted source of truth, with search, admin approvals, and agent management.",
      11: "SmartTech built an all-in-one real estate web platform with wallets, rental loans, rental savings, and smart property search.",
      7: "SmartTech built a self-paced discipleship web platform with course management, a virtual classroom, and community tools for students and tutors alike.",
    },
    outcomePanelColors: {
      6: "linear-gradient(160deg, #0c2f4a 0%, #1481c9 100%)",
      8: "linear-gradient(160deg, #0f3d3a 0%, #0d9488 100%)",
      11: "linear-gradient(160deg, #241455 0%, #6d28d9 100%)",
      7: "linear-gradient(160deg, #7c2d12 0%, #c2410c 100%)",
    },
    industriesTitle: "Industries we bring online first",
    industriesDesc: "Backed by real, shipped work across a range of industries, SmartTech builds web products that understand each industry's own constraints, not a copy-pasted template.",
    industries: [
      { title: "Real Estate", desc: "Listing, search, and transaction platforms that turn browsing into booked deals." },
      { title: "PropTech", desc: "Data platforms that turn fragmented property records into one trusted source of truth." },
      { title: "FinTech", desc: "Secure, compliant web platforms for trading, payments, and portfolio management." },
      { title: "Logistics", desc: "Dispatch and tracking dashboards that keep fleets and freight visible in real time." },
      { title: "Education", desc: "Course, cohort, and classroom platforms built for real engagement, not just uploads." },
      { title: "Faith & Community", desc: "Membership, giving, and content platforms built for daily engagement at scale." },
      { title: "E-Commerce", desc: "Storefronts and admin tooling built to convert and to stay fast under real traffic." },
      { title: "Enterprise SaaS", desc: "Internal tools and dashboards that replace spreadsheets with real workflows." },
    ],
    ctaTitle: "Ready to launch your next web app?",
    ctaDesc: "Tell us what you're building — we'll bring the engineering and design to ship it right.",
    ctaStatValue: "180+",
    ctaStatLabel: "Web projects delivered",
    faqKey: "web_dev_faqs",
  },

  "blockchain-development": {
    accent: "124 58 237",
    titleAccent: "Blockchain",
    titleRest: "Development Services",
    heroDesc:
      "At SmartTech, we empower your business to step confidently into the future with bespoke Web3 development services. We transform enterprises and disrupt industries by delivering custom blockchain solutions that overcome longstanding challenges while unlocking exciting new opportunities for growth and innovation.",
    heroMode: "collage",
    tileShape: "browser",
    heroLayout: "2",
    heroTiles: [
      tile("/app_images/projects/digistate/website/investor dashboard.png", "Digistate tokenized real estate dashboard"),
      tile("/app_images/projects/JPGC/SmartTechProject_japaul_gold_coin.png", "JPGold Coin platform"),
      tile("/app_images/projects/jpgc_app/jpgc_dashboard.png", "JPGC App dashboard"),
      tile("/app_images/projects/jpgc_app/jpg_nft_marketplace.png", "JPGC NFT marketplace"),
    ],
    whyImage: image_url("/app_images/services/service_art/blockchain-development.webp", true),
    whyImageAlt: "Instrument diagram of a linked block ledger, plotted for SmartTech's blockchain development practice",
    faqImage: image_url("/app_images/services/service_art/blockchain-development.webp", true),
    faqImageAlt: "Instrument diagram of a linked block ledger, plotted for SmartTech's blockchain development practice",
    countersTitle: "Leading global brands rely on our proven expertise.",
    countersDesc: "For over 13 years, SmartTech has been the trusted partner of global brands, delivering exceptional blockchain solutions through our competent team.",
    allInOneTitle: "Pioneering innovation with tailored blockchain solutions",
    servicesKey: "blockchain_dev_services",
    processDesc: "From ideation to implementation and beyond, our expert-driven methodology guarantees that your blockchain applications are secure, scalable, and customized to meet your specific needs.",
    procedureKey: "blockchain_dev_procedure",
    whyTitle: "Why SmartTech for your Blockchain Development",
    whyDesc: "We build blockchain products that ship — tokenized assets, on-chain trading, and wallets running in production today, not just on a whitepaper.",
    whyPoints: [
      "With over 13 years of industry experience",
      "Skilled in deploying public blockchain networks",
      "Expert in crafting software solutions tailored for various industries",
      "Excellent in implementing secure hashing and key exchange protocols",
      "Custom blockchain solutions designed to align with your unique goals",
      "Built for seamless future scalability",
      "Agile-driven project management",
      "Security and compliance built in, not bolted on",
    ],
    outcomesTitle: "Blockchain products we've shipped and scaled",
    outcomesDesc: "A look inside real tokenization, trading, and wallet platforms our team designed, engineered, and shipped.",
    outcomeProjectIds: [1, 2, 5],
    outcomeHighlights: {
      1: "SmartTech built a blockchain-powered real estate platform, giving investors fractional ownership, real-time secondary trading, and a custom exchange.",
      2: "SmartTech built the platform behind a gold-backed stablecoin, listed on exchanges like BitMart, serving as a universal medium for exchange and investment.",
      5: "SmartTech built the official JPGC platform where investors buy, manage, and sell tokens and NFTs across web, mobile, and admin.",
    },
    outcomePanelColors: {
      1: "linear-gradient(160deg, #0b1a3a 0%, #14275c 100%)",
      2: "linear-gradient(160deg, #78350f 0%, #d97706 100%)",
      5: "linear-gradient(160deg, #3b1d5c 0%, #7c3aed 100%)",
    },
    industriesTitle: "Industries we bring on-chain",
    industriesDesc: "Our groundbreaking blockchain technology is transforming industries, expanding possibilities, and empowering global enterprises to achieve new heights of success.",
    industries: [
      { title: "Real Estate", desc: "Fractional ownership and tokenized property trading, built for real regulators." },
      { title: "FinTech", desc: "Stablecoins, exchanges, and wallets engineered for real transaction volume." },
      { title: "Web3 & Digital Assets", desc: "Token launches, NFT platforms, and on-chain marketplaces that actually ship." },
      { title: "Supply Chain", desc: "Provenance and traceability records that can't be quietly rewritten." },
      { title: "Gaming", desc: "Play-to-own economies and in-game asset ownership built to last." },
      { title: "Public Sector", desc: "Transparent, auditable record-keeping for institutions that need to prove it." },
    ],
    ctaTitle: "Ready to build your Web3 product?",
    ctaDesc: "Tell us what you're building — we'll bring the engineering and security expertise to ship it right.",
    ctaStatValue: "13+",
    ctaStatLabel: "Years building on-chain",
    faqKey: "blockchain_dev_faqs",
  },

  "nft-marketplace-development": {
    accent: "217 119 6",
    titleAccent: "NFT Marketplace",
    titleRest: "Development Service",
    heroDesc:
      "Transforming visionary ideas into high-value digital assets, we specialize in designing bespoke NFT marketplaces, immersive gaming platforms, and dynamic ecosystems that empower communities and drive sustainable growth. Our innovative solutions seamlessly merge cutting-edge technology with creative flair.",
    heroMode: "collage",
    tileShape: "browser",
    heroLayout: "3",
    heroTiles: [
      tile("/app_images/projects/jpgc_app/jpg_nft_marketplace.png", "JPGC NFT marketplace"),
      tile("/app_images/projects/jpgc_app/jpg_nft_management.png", "JPGC NFT management"),
      tile("/app_images/projects/JPGC/jpgc_nft_dashboard.png", "JPGC NFT dashboard"),
      tile("/app_images/projects/jpgc_app/jpgc_checkout.png", "JPGC checkout flow"),
    ],
    whyImage: image_url("/app_images/services/service_art/nft-marketplace-development.webp", true),
    whyImageAlt: "Instrument diagram of a provenance authentication seal, plotted for SmartTech's NFT marketplace practice",
    faqImage: image_url("/app_images/services/service_art/nft-marketplace-development.webp", true),
    faqImageAlt: "Instrument diagram of a provenance authentication seal, plotted for SmartTech's NFT marketplace practice",
    countersTitle: "A globally recognized leader in cutting-edge NFT marketplace solutions",
    countersDesc: "For over 13 years, SmartTech has been the trusted partner of global brands, delivering exceptional NFT marketplaces.",
    allInOneTitle: "Our NFT marketplace development services",
    servicesKey: "nft_marketplace_dev_services",
    processDesc: "Using our proven methodology, we craft feature-rich, secure NFT marketplaces that elevate the trading experience with robust, multi-layered security protocols.",
    procedureKey: "nft_marketplace_dev_procedure",
    whyTitle: "Why choose our NFT development services?",
    whyDesc: "We blend innovation with customization to design NFT marketplace solutions that align perfectly with your vision, ensuring a seamless and tailored experience.",
    whyPoints: [
      "13+ years of industry experience",
      "400+ completed projects",
      "250+ blockchain developers & architects",
      "Multi-blockchain support",
      "Advanced security measures",
      "User-centric design for seamless experiences and engagement",
      "Long-term support and continuous optimization",
    ],
    outcomesTitle: "NFT platforms we've shipped and scaled",
    outcomesDesc: "A look inside real NFT marketplace and management tooling our team designed, engineered, and shipped.",
    outcomeProjectIds: [5, 2],
    outcomeHighlights: {
      5: "SmartTech built the JPGC platform's NFT marketplace and management suite, letting holders buy, manage, and sell NFTs alongside their token portfolio.",
      2: "SmartTech built the wider JPGold Coin platform, the token ecosystem an NFT marketplace like this one plugs directly into.",
    },
    outcomePanelColors: {
      5: "linear-gradient(160deg, #3b1d5c 0%, #7c3aed 100%)",
      2: "linear-gradient(160deg, #78350f 0%, #d97706 100%)",
    },
    industriesTitle: "Industries we bring on-chain",
    industriesDesc: "We create innovative NFT marketplace development services that empower industries to make an impact and achieve measurable results.",
    industries: [
      { title: "Web3 & Digital Assets", desc: "Token launches and NFT platforms engineered for real trading volume." },
      { title: "Gaming", desc: "Play-to-own economies and in-game asset marketplaces built to last." },
      { title: "Art & Collectibles", desc: "Creator storefronts with minting, royalties, and secondary sales built in." },
      { title: "Music & Media", desc: "Rights-managed digital media marketplaces for creators and labels." },
      { title: "Real Estate", desc: "Tokenized property and fractional-ownership marketplaces." },
      { title: "Fashion & Apparel", desc: "Phygital drops and brand collectible marketplaces." },
    ],
    ctaTitle: "Ready to launch your NFT marketplace?",
    ctaDesc: "Tell us what you're building — we'll bring the engineering and security expertise to ship it right.",
    ctaStatValue: "400+",
    ctaStatLabel: "Projects completed",
    faqKey: "nft_marketplace_dev_faqs",
  },

  "mvp-development": {
    accent: "13 148 136",
    titleAccent: "Professional MVP",
    titleRest: "Development Services",
    heroDesc:
      "At SmartTech, we expertly transform your bold ideas into robust, market-ready digital solutions by leveraging our time-tested MVP development services, enabling you to refine your vision, rapidly gather user feedback, minimize risks, and secure a competitive edge in a fast-paced market.",
    heroMode: "collage",
    tileShape: "browser",
    heroLayout: "4",
    heroTiles: [
      tile("/app_images/projects/dts/homepage.png", "DTS discipleship platform"),
      tile("/app_images/projects/flatshare/dashboard.png", "Flatshare dashboard"),
      tile("/app_images/projects/geoplox/property_search.png", "Geoplox property search"),
      tile("/app_images/projects/xabi/dashboard.png", "Xabi dashboard"),
    ],
    whyImage: image_url("/app_images/services/service_art/mvp-development.webp", true),
    whyImageAlt: "Instrument diagram of a build-measure-learn iteration loop, plotted for SmartTech's MVP development practice",
    faqImage: image_url("/app_images/services/service_art/mvp-development.webp", true),
    faqImageAlt: "Instrument diagram of a build-measure-learn iteration loop, plotted for SmartTech's MVP development practice",
    countersTitle: "A globally recognized leader in professional MVP development.",
    countersDesc: "For over 15 years, SmartTech has been the trusted partner of global brands, delivering professional MVP development services through our competent team.",
    allInOneTitle: "Our MVP development services",
    servicesKey: "mvp_development_services",
    processDesc: "Our development teams embrace an agile methodology, fostering enhanced flexibility, improved communication, and accelerated delivery, ensuring your product initiatives are executed efficiently and adaptively.",
    procedureKey: "mvp_development_service_procedure",
    whyTitle: "Key benefits of our MVP development services",
    whyDesc: "SmartTech's MVP development services empower you to validate your product idea efficiently, minimize development costs, accelerate time-to-market, and gather real user feedback.",
    whyPoints: [
      "Rapid development cycles without compromising on quality",
      "Cost-effective delivery of high-quality products",
      "Scalable solutions designed to grow with your business",
      "User-centric design for seamless experiences and engagement",
      "Seasoned developers and designers on every build",
    ],
    outcomesTitle: "MVPs we've shipped and scaled",
    outcomesDesc: "A look inside real products our team took from first idea to a live, working platform, fast.",
    outcomeProjectIds: [3, 6],
    outcomeHighlights: {
      3: "SmartTech shipped Lodapoint's ride-hailing and freight logistics MVP, connecting cargo owners and passengers with verified drivers from day one.",
      6: "SmartTech shipped Flatshare's flatmate-matching MVP — profiles, messaging, and listing filters — validated with real users fast.",
    },
    outcomePanelColors: {
      3: "linear-gradient(160deg, #78350f 0%, #d97706 100%)",
      6: "linear-gradient(160deg, #0c2f4a 0%, #1481c9 100%)",
    },
    industriesTitle: "Industries we help launch fast",
    industriesDesc: "We create innovative MVP development services that empower industries to make an impact, streamline critical processes, and achieve measurable results.",
    industries: [
      { title: "Logistics", desc: "Dispatch and tracking MVPs validated with real drivers and real cargo." },
      { title: "PropTech", desc: "Listing and matching platforms validated with real renters fast." },
      { title: "FinTech", desc: "Lean, compliant financial product MVPs ready for a first real cohort of users." },
      { title: "Healthcare", desc: "Patient-facing MVPs built to validate demand before a full clinical rollout." },
      { title: "EdTech", desc: "Course and cohort MVPs built to prove engagement before scaling content." },
      { title: "Marketplaces", desc: "Two-sided marketplace MVPs built to prove liquidity before scaling supply." },
    ],
    ctaTitle: "Ready to validate your next big idea?",
    ctaDesc: "Tell us what you're building — we'll help you ship a real MVP, not a slide deck.",
    ctaStatValue: "100+",
    ctaStatLabel: "MVPs shipped",
    faqKey: "mvp_development_service_faqs",
  },

  "game-development": {
    accent: "220 38 38",
    titleAccent: "2D, 3D, & NFT Game Development",
    titleRest: "with Unity or Unreal Engine",
    heroDesc:
      "From concept to launch, our award-winning team leverages Unity and Unreal Engine to build immersive 2D, 3D, and NFT games that seamlessly blend stunning visuals, intricate storytelling, dynamic gameplay, and innovative play-to-own mechanics for players across mobile, VR, PC, and console platforms.",
    heroMode: "single",
    heroVisual: <GameHeroVisual />,
    whyImage: image_url("/app_images/services/service_art/game-development.webp", true),
    whyImageAlt: "Instrument diagram of a control-input mapping scheme, plotted for SmartTech's game development practice",
    faqImage: image_url("/app_images/services/service_art/game-development.webp", true),
    faqImageAlt: "Instrument diagram of a control-input mapping scheme, plotted for SmartTech's game development practice",
    countersTitle: "Your trusted game development company",
    countersDesc: "For over 9 years, SmartTech has been the trusted partner of global brands, delivering exceptional 2D, 3D and NFT games that engage players across mobile, VR, PC, and console platforms.",
    allInOneTitle: "Why choose SmartTech for your 2D and 3D game development",
    servicesKey: "game_dev_services",
    processDesc: "From ideation to implementation and beyond, our expert-driven methodology guarantees that your game is secure, scalable, and customized to meet your specific needs.",
    procedureKey: "game_dev_service_procedure",
    whyTitle: "Your 2D/3D game development dream team",
    whyDesc: "A full production team, not a single freelancer — every role a real game studio needs, on every build.",
    whyPoints: [
      "Project Manager — orchestrating seamless communication and on-time delivery",
      "Game Producer — merging your ideas with industry trends into something commercially astute",
      "2D/3D Artists — pushing the boundaries of your game's visuals",
      "Game Designer — crafting captivating stories, characters, and mechanics",
      "Game Developers — turning creative vision into elegant, performant code",
      "Backend Developers — engineering multiplayer, online features, and data storage",
      "QA Engineers — eliminating bugs before they ever reach a player",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our game builds land",
    industriesDesc: "We build games and gamified experiences that empower industries to engage players and customers alike, not just entertainment studios.",
    industries: [
      { title: "Entertainment & Studios", desc: "Full 2D/3D titles built for mobile, PC, and console." },
      { title: "Web3 & NFT Gaming", desc: "Play-to-own economies and in-game asset ownership." },
      { title: "EdTech", desc: "Gamified learning experiences that keep students coming back." },
      { title: "Marketing & Brand", desc: "Branded mini-games and interactive campaigns built to convert." },
      { title: "Fitness & Wellness", desc: "Gamified habit and activity apps built for daily engagement." },
    ],
    ctaTitle: "Ready to build your next game?",
    ctaDesc: "Tell us what you're building — we'll bring the engineering and design to ship it right.",
    ctaStatValue: "9+",
    ctaStatLabel: "Years in game development",
    faqKey: "game_dev_faqs",
  },

  "3D-animations": {
    accent: "99 102 241",
    titleAccent: "3D Animation",
    titleRest: "Services",
    heroDesc:
      "SmartTech is a cutting-edge animation production company renowned for creating modern, visually striking 3D animated videos. We transform your vision into breathtaking reality with mesmerizing 3D animation services — cinematic game trailers, dynamic product animations, training videos, commercial productions, and architectural renderings.",
    heroMode: "single",
    heroImage: image_url("/app_images/services/service_images/smarttech_3d_animation.png", true),
    heroImageAlt: "SmartTech 3D animation services",
    whyImage: image_url("/app_images/services/service_art/3D-animations.webp", true),
    whyImageAlt: "Instrument diagram of an animation easing curve plotted across a frame timeline, for SmartTech's 3D animation practice",
    faqImage: image_url("/app_images/services/service_art/3D-animations.webp", true),
    faqImageAlt: "Instrument diagram of an animation easing curve plotted across a frame timeline, for SmartTech's 3D animation practice",
    countersTitle: "Why our clients love us",
    countersDesc: "Rest easy knowing our stellar animation production record speaks for itself, with loads of successful projects, delighted clients, and industry-leading turnaround times.",
    allInOneTitle: "Why choose us for your 3D animation",
    servicesKey: "three_dimentional_animation_services",
    processDesc: "From storyboard to final render, our expert-driven methodology guarantees your animation is polished, on-brand, and delivered on schedule.",
    procedureKey: "three_dimentional_animation_service_procedure",
    whyTitle: "Your 3D animation dream team",
    whyDesc: "A full production team, not a single freelancer — every role a real animation studio needs, on every build.",
    whyPoints: [
      "Project Manager — orchestrating seamless communication and on-time delivery",
      "Art Directors — establishing a compelling, consistent visual style",
      "3D Animation Team Leads — overseeing every phase from concept to final cut",
      "3D Artists & Modelers — crafting realistic characters, environments, and props",
      "3D Animators — building dynamic character movement and animation",
      "VFX & Rendering Experts — enhancing every frame with advanced lighting and effects",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our animation work lands",
    industriesDesc: "We create 3D animation that empowers brands to make an impact, not just cinematic showreels.",
    industries: [
      { title: "Advertising & Brand", desc: "Product and commercial animation built to convert attention into sales." },
      { title: "Gaming", desc: "Cinematic trailers and in-game cutscenes built to hype a launch." },
      { title: "Real Estate", desc: "Architectural renderings and fly-throughs that sell a space before it's built." },
      { title: "Healthcare", desc: "Medical explainer animation that makes complex procedures easy to follow." },
      { title: "Manufacturing", desc: "Product animation that shows how something works before it ships." },
    ],
    ctaTitle: "Ready to bring your vision to life?",
    ctaDesc: "Tell us what you're building — we'll bring the artistry and engineering to render it right.",
    ctaStatValue: "9+",
    ctaStatLabel: "Years in animation production",
    faqKey: "three_dimentional_animation_service_faqs",
  },

  "3D-modeling": {
    accent: "8 145 178",
    titleAccent: "3D Modeling",
    titleRest: "Services",
    heroDesc:
      "Elevate your brand by seamlessly transforming real products into captivating virtual experiences with our detailed, affordable 3D modeling services — an innovative solution for dynamic marketing research, rapid prototyping, and compelling product promotion through meticulously crafted low-poly and high-poly renderings.",
    heroMode: "single",
    heroImage: image_url("/app_images/services/service_images/smarttech_3d_modeling.png", true),
    heroImageAlt: "SmartTech 3D modeling services",
    whyImage: image_url("/app_images/services/service_art/3D-modeling.webp", true),
    whyImageAlt: "Instrument diagram of a triangulated mesh topology with axis gizmo, for SmartTech's 3D modeling practice",
    faqImage: image_url("/app_images/services/service_art/3D-modeling.webp", true),
    faqImageAlt: "Instrument diagram of a triangulated mesh topology with axis gizmo, for SmartTech's 3D modeling practice",
    countersTitle: "Why our clients love us",
    countersDesc: "Rest easy knowing our stellar production record speaks for itself, with loads of successful projects, delighted clients, and industry-leading turnaround times.",
    allInOneTitle: "Why choose us for your 3D modeling",
    servicesKey: "three_dimentional_modeling_services",
    processDesc: "From reference gathering to final texture pass, our expert-driven methodology guarantees your models are accurate, optimized, and delivered on schedule.",
    procedureKey: "three_dimentional_modeling_service_procedure",
    whyTitle: "Why work with our 3D modeling team",
    whyDesc: "The same modeling discipline behind our shipped game and animation work, applied to your product, character, or environment.",
    whyPoints: [
      "Low-poly and high-poly modeling for any target platform",
      "Game-ready assets optimized for real-time rendering",
      "Photoreal product renders for marketing and e-commerce",
      "Texturing and material work built for physically-based rendering",
      "Fast turnaround without cutting corners on quality",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our modeling work lands",
    industriesDesc: "We create 3D models that empower brands to visualize products before they exist in the real world.",
    industries: [
      { title: "E-Commerce", desc: "Photoreal product renders that outperform photography." },
      { title: "Gaming", desc: "Game-ready character, prop, and environment assets." },
      { title: "Manufacturing", desc: "Prototype visualization before a single physical unit is built." },
      { title: "Real Estate", desc: "Furnished, staged virtual interiors for listings and marketing." },
      { title: "Advertising & Brand", desc: "Hero product renders for campaigns and packaging." },
    ],
    ctaTitle: "Ready to model your next product?",
    ctaDesc: "Tell us what you're building — we'll bring the craft to render it right.",
    ctaStatValue: "250+",
    ctaStatLabel: "Assets modeled and rendered",
    faqKey: "three_dimentional_modeling_service_faqs",
  },

  "product-design": {
    accent: "219 39 119",
    titleAccent: "Product Design",
    titleRest: "Services",
    heroDesc:
      "Captivate your customers and build unwavering brand loyalty with designs that truly resonate. Our seasoned design experts transform your ideas into visually striking, user-centric solutions, where every detail is meticulously refined to enhance functionality and elevate the user experience.",
    heroMode: "single",
    heroImage: image_url("/app_images/services/service_images/smarttech_uiux.png", true),
    heroImageAlt: "SmartTech product design services",
    whyImage: image_url("/app_images/services/service_art/product-design.webp", true),
    whyImageAlt: "Instrument diagram of a modular type scale and spacing grid, for SmartTech's product design practice",
    faqImage: image_url("/app_images/services/service_art/product-design.webp", true),
    faqImageAlt: "Instrument diagram of a modular type scale and spacing grid, for SmartTech's product design practice",
    countersTitle: "Why our clients love us",
    countersDesc: "For over 10 years, SmartTech has been the trusted partner of global brands, delivering exceptional product designs through our competent team.",
    allInOneTitle: "Comprehensive product design services",
    servicesKey: "product_design_services",
    processDesc: "Armed with cutting-edge design tools, proven methodologies, and a focus on human experiences, we empower you to create products that truly resonate with your customers.",
    procedureKey: "product_design_service_procedure",
    whyTitle: "Why work with us",
    whyDesc: "With over 10 years of expertise and a track record of hundreds of successful projects, SmartTech is the go-to partner for global brands.",
    whyPoints: [
      "User-centric excellence — intuitive interfaces that truly resonate",
      "Full-service expertise from initial concept through full-scale development",
      "Innovative prototyping to visualize and refine your vision early",
      "Rigorous branding and technology standards on every screen",
      "Strategic redesign that audits your product and your competition",
      "A competitive digital advantage aligned with your business goals",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our design work lands",
    industriesDesc: "We design digital products that empower industries to make an impact, streamline critical processes, and achieve measurable results.",
    industries: [
      { title: "FinTech", desc: "Trust-first interfaces for money movement and investing." },
      { title: "Real Estate", desc: "Listing and transaction flows designed to convert browsers into buyers." },
      { title: "Healthcare", desc: "Patient-facing design that stays clear under real stress." },
      { title: "E-Commerce", desc: "Storefront and checkout design built to reduce drop-off." },
      { title: "Education", desc: "Learning experiences designed to keep students coming back." },
      { title: "Enterprise SaaS", desc: "Internal tools redesigned around how teams actually work." },
    ],
    ctaTitle: "Ready to design your next product?",
    ctaDesc: "Tell us what you're building — we'll bring the design craft to make it resonate.",
    ctaStatValue: "180+",
    ctaStatLabel: "Products designed",
    faqKey: "product_design_faqs",
  },

  "ai-development": {
    accent: "5 150 105",
    titleAccent: "Artificial Intelligence",
    titleRest: "Development Services",
    heroDesc:
      "At SmartTech, we harness cutting-edge AI solutions that not only streamline your operations and boost efficiency but also transform your data into actionable insights, empowering your business to achieve sustainable growth and maintain a decisive edge in a rapidly evolving market.",
    heroMode: "single",
    heroImage: image_url("/app_images/services/service_images/smarttech_ai_development.png", true),
    heroImageAlt: "SmartTech AI development services",
    whyImage: image_url("/app_images/services/service_art/ai-development.webp", true),
    whyImageAlt: "Instrument diagram of a weighted neural network's layers and connections, for SmartTech's AI development practice",
    faqImage: image_url("/app_images/services/service_art/ai-development.webp", true),
    faqImageAlt: "Instrument diagram of a weighted neural network's layers and connections, for SmartTech's AI development practice",
    countersTitle: "A globally recognized leader in AI development services.",
    countersDesc: "For years, SmartTech has been the trusted partner of global brands, delivering professional AI development services through our competent team.",
    allInOneTitle: "Our AI development services",
    servicesKey: "ai_development_services",
    processDesc: "From data readiness to a deployed model, our expert-driven methodology keeps every AI build grounded in your actual data and your actual users.",
    procedureKey: "ai_development_service_procedure",
    whyTitle: "Why SmartTech for your AI development",
    whyDesc: "Fast, efficient, and scalable AI development, backed by a user-centered design approach on every build.",
    whyPoints: [
      "Future-ready AI solutions tailored to your evolving needs",
      "Scalable systems that streamline operations and drive growth",
      "Automation that frees your team for strategic work",
      "Customized models built around your actual business challenges",
      "Dedicated support ensuring optimal performance after launch",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our AI work lands",
    industriesDesc: "We build AI systems that empower industries to make faster, better-informed decisions, not generic chatbots.",
    industries: [
      { title: "FinTech", desc: "Fraud detection and risk-scoring models built for real transaction volume." },
      { title: "E-Commerce", desc: "Recommendation and search systems that actually lift conversion." },
      { title: "Healthcare", desc: "Decision-support tooling built with real clinical constraints in mind." },
      { title: "Logistics", desc: "Route and demand forecasting models that cut real operating cost." },
      { title: "Customer Support", desc: "AI-assisted support tooling that resolves, not just deflects." },
      { title: "Manufacturing", desc: "Predictive maintenance models built on real sensor data." },
    ],
    ctaTitle: "Ready to put AI to work?",
    ctaDesc: "Tell us what you're building — we'll bring the engineering to make it real.",
    ctaStatValue: "8+",
    ctaStatLabel: "Years building AI systems",
    faqKey: "ai_development_service_faqs",
  },

  "2D-animations": {
    accent: "234 88 12",
    titleAccent: "2D Animation",
    titleRest: "Services",
    heroDesc:
      "Ignite your vision with SmartTech's seasoned experts, turning your boldest ideas into captivating 2D animations and mesmerizing visual effects that empower startups and industry leaders to outshine the competition, leave an unforgettable brand impression, and achieve unparalleled success.",
    heroMode: "single",
    heroImage: image_url("/app_images/services/service_images/smarttech_2d_animations.png", true),
    heroImageAlt: "SmartTech 2D animation services",
    whyImage: image_url("/app_images/services/service_art/2D-animations.webp", true),
    whyImageAlt: "Instrument diagram of an onion-skin frame sequence, for SmartTech's 2D animation practice",
    faqImage: image_url("/app_images/services/service_art/2D-animations.webp", true),
    faqImageAlt: "Instrument diagram of an onion-skin frame sequence, for SmartTech's 2D animation practice",
    countersTitle: "Why our clients love us",
    countersDesc: "Rest assured, our proven legacy in animation production, marked by hundreds of successful projects and glowing client testimonials, guarantees that your vision is executed with unmatched excellence and efficiency.",
    allInOneTitle: "Why choose us for your 2D animation",
    servicesKey: "two_dimentional_animation_services",
    processDesc: "From storyboard to final render, our expert-driven methodology guarantees your animation is polished, on-brand, and delivered on schedule.",
    procedureKey: "two_dimentional_animation_service_procedure",
    whyTitle: "Your 2D animation dream team",
    whyDesc: "A full production team, not a single freelancer — every role a real animation studio needs, on every build.",
    whyPoints: [
      "Project Manager — orchestrating seamless communication and on-time delivery",
      "Art Director — establishing a compelling, consistent visual style",
      "2D Animation Team Lead — overseeing every phase from concept to final cut",
      "2D Artists — crafting characters, environments, and props tailored to your vision",
      "2D Animators — animating every expression, gesture, and movement with precision",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our animation work lands",
    industriesDesc: "We create 2D animation that empowers brands to make an impact, not just cartoons.",
    industries: [
      { title: "Advertising & Brand", desc: "Explainer and product animation built to convert attention into sales." },
      { title: "EdTech", desc: "Animated learning content that keeps students engaged." },
      { title: "Entertainment & Media", desc: "Character animation and shorts built for a real audience." },
      { title: "Healthcare", desc: "Medical explainer animation that makes complex topics easy to follow." },
      { title: "Gaming", desc: "2D character and UI animation built for real-time engines." },
    ],
    ctaTitle: "Ready to bring your vision to life?",
    ctaDesc: "Tell us what you're building — we'll bring the artistry and engineering to animate it right.",
    ctaStatValue: "9+",
    ctaStatLabel: "Years in animation production",
    faqKey: "two_dimentional_animation_service_faqs",
  },

  "2D-arts": {
    accent: "190 24 93",
    titleAccent: "2D Art",
    titleRest: "Services",
    heroDesc:
      "Blending sleek corporate visuals with whimsical illustrations, our creative team crafts captivating, bespoke 2D art that transforms your ideas into vibrant visuals, elevating your brand and deeply engaging your audience across tech, healthcare, entertainment, and beyond.",
    heroMode: "single",
    heroImage: image_url("/app_images/services/service_images/smarttech_2d_arts.png", true),
    heroImageAlt: "SmartTech 2D art services",
    whyImage: image_url("/app_images/services/service_art/2D-arts.webp", true),
    whyImageAlt: "Instrument diagram of a chroma calibration swatch grid with a gesture brush stroke, for SmartTech's 2D art practice",
    faqImage: image_url("/app_images/services/service_art/2D-arts.webp", true),
    faqImageAlt: "Instrument diagram of a chroma calibration swatch grid with a gesture brush stroke, for SmartTech's 2D art practice",
    countersTitle: "Why our clients love us",
    countersDesc: "Rest easy knowing our stellar production record speaks for itself, with loads of successful projects, delighted clients, and industry-leading turnaround times.",
    allInOneTitle: "Why choose us for your 2D art creation",
    servicesKey: "two_dimentional_art_services",
    processDesc: "From concept sketches to final polished art, our expert-driven methodology guarantees your visuals are on-brand and delivered on schedule.",
    procedureKey: "two_dimentional_art_service_procedure",
    whyTitle: "Why work with our 2D art team",
    whyDesc: "A dedicated illustration and concept-art team, not a single freelancer, on every build.",
    whyPoints: [
      "Bespoke character and environment concept art",
      "Brand-consistent illustration systems, not one-off pieces",
      "Style flexibility — from corporate-clean to fully whimsical",
      "Game-ready and print-ready art delivered in the formats you need",
      "Fast turnaround without cutting corners on quality",
    ],
    outcomeProjectIds: [],
    industriesTitle: "Where our art work lands",
    industriesDesc: "We create 2D art that empowers brands to stand out, not just pretty pictures.",
    industries: [
      { title: "Advertising & Brand", desc: "Illustration systems built to make a brand instantly recognizable." },
      { title: "Gaming", desc: "Concept art and 2D game assets built for production pipelines." },
      { title: "EdTech", desc: "Illustrated learning content built to hold a young audience's attention." },
      { title: "Entertainment & Media", desc: "Character and story art built for publishing and animation." },
      { title: "Healthcare", desc: "Clear, friendly illustration that makes medical content approachable." },
    ],
    ctaTitle: "Ready to bring your vision to life?",
    ctaDesc: "Tell us what you're building — we'll bring the artistry to illustrate it right.",
    ctaStatValue: "250+",
    ctaStatLabel: "Artworks delivered",
    faqKey: "two_dimentional_art_service_faqs",
  },
};

export const getServicePage = (slug) => SERVICE_PAGES[slug];
