import { ROUTE } from "@/route/app_routes.js";

// Single source of truth for every "Industries we serve" page — powers the
// header's Industries mega-menu (name/icon/href only) AND the 16 industry
// landing pages (full content). `projectIds` links to my_data/projects/
// projects.js entries with a genuine tie to that industry — left empty
// where SmartTech has no shipped project in that vertical, rather than
// fabricating a case study.
export const INDUSTRIES = [
  {
    slug: "real-estate",
    href: ROUTE.real_estate_industry,
    name: "Real Estate",
    icon: "feather-home",
    accent: "185,102,231",
    heroImage: "/app_images/industries/real-estate.webp",
    eyebrow: "PropTech & Real Estate",
    heroTitle: "Software that turns property into a liquid, trackable asset",
    heroDesc:
      "From tokenized ownership to listing platforms and tenant portals, we build the software layer that modern real estate businesses run on.",
    stats: [
      { value: "4", label: "Real estate platforms shipped" },
      { value: "3", label: "Blockchain-backed asset systems" },
      { value: "100%", label: "Mobile-first delivery" },
    ],
    challenges: [
      { title: "Illiquid, paperwork-heavy transactions", desc: "Buying, selling, and fractionalizing property still runs on manual paperwork and slow settlement cycles." },
      { title: "Fragmented listing and tenant data", desc: "Listings, leases, payments, and maintenance requests live in disconnected spreadsheets and legacy tools." },
      { title: "Low trust in remote transactions", desc: "Buyers and investors hesitate to commit capital without verifiable, transparent records of ownership and history." },
    ],
    capabilities: [
      { title: "Tokenized ownership platforms", desc: "Fractional investment and secondary-market trading built on audited smart contracts." },
      { title: "Listing & discovery portals", desc: "Fast, filterable property search with map views, saved searches, and lead capture." },
      { title: "Tenant & property management", desc: "Rent collection, maintenance requests, and lease tracking in one dashboard." },
      { title: "Virtual tours & AR walkthroughs", desc: "Immersive property previews that convert remote buyers faster." },
      { title: "CRM & agent tooling", desc: "Pipeline tracking purpose-built for brokerages and independent agents." },
      { title: "Secure document & e-signing flows", desc: "Contracts, disclosures, and closing documents handled end-to-end online." },
    ],
    whyPoints: [
      "We've shipped a blockchain-tokenized real estate exchange from scratch",
      "Native mobile and admin suite delivery under one roof",
      "Deep experience with escrow, payments, and compliance flows",
      "Design systems built for trust — critical for high-value transactions",
      "Post-launch support that scales with your transaction volume",
    ],
    faqs: [
      { q: "Can you build tokenized or fractional-ownership real estate platforms?", a: "Yes — we designed and built Digistate, a blockchain-powered real estate exchange supporting fractional investment and secondary-market trading, from architecture through native mobile apps." },
      { q: "Do you integrate with MLS or third-party listing data?", a: "We regularly integrate listing feeds, geocoding, and map providers into custom-built portals so your platform stays current without manual data entry." },
      { q: "How do you handle payments and escrow for property transactions?", a: "We design payment and escrow flows around your regulatory environment, integrating trusted payment/escrow providers or custom smart-contract logic where blockchain settlement is required." },
      { q: "Can you modernize an existing property management tool?", a: "Absolutely — we regularly take over legacy real estate platforms, re-architecting for performance and adding mobile apps without disrupting live operations." },
    ],
    projectIds: [1, 6, 8, 11],
  },
  {
    slug: "finance",
    href: ROUTE.finance_industry,
    name: "Finance",
    icon: "feather-dollar-sign",
    accent: "39,120,255",
    heroImage: "/app_images/industries/finance.webp",
    eyebrow: "Fintech & Financial Services",
    heroTitle: "Financial software engineered for trust, speed, and scale",
    heroDesc:
      "We build trading platforms, wallets, and financial dashboards that move real money — with the security posture and precision that demands.",
    stats: [
      { value: "5+", label: "Financial dashboards delivered" },
      { value: "10+", label: "Years building secure systems" },
      { value: "0", label: "Compromised production systems" },
    ],
    challenges: [
      { title: "Zero tolerance for downtime or data loss", desc: "Financial software has to be right every single time — there's no acceptable margin for a broken transaction." },
      { title: "Complex, evolving compliance requirements", desc: "KYC, AML, and regional financial regulations shift constantly and must be built into the product, not bolted on." },
      { title: "Legacy core banking integrations", desc: "New products still have to talk to decades-old core banking and payment infrastructure." },
    ],
    capabilities: [
      { title: "Trading & investment platforms", desc: "Real-time portfolio tracking, order execution, and market data at low latency." },
      { title: "Digital wallets & payments", desc: "Multi-currency wallets with card, bank, and on-chain payment rails." },
      { title: "KYC & compliance workflows", desc: "Identity verification and audit trails built to regulatory spec." },
      { title: "Lending & savings products", desc: "Loan origination, savings goals, and interest-bearing account logic." },
      { title: "Fraud detection & monitoring", desc: "Rule-based and behavioral anomaly detection layered into transaction flows." },
      { title: "Admin & risk dashboards", desc: "Real-time visibility for finance and risk teams across every transaction." },
    ],
    whyPoints: [
      "Built and shipped a live investment and trading platform end-to-end",
      "Security-first architecture: encryption, audit trails, least-privilege access by default",
      "Experience across blockchain-settled and traditional rails",
      "Native iOS/Android delivery for consumer-facing finance apps",
      "Rigorous QA — our finance builds ship with dedicated QA engineering, not an afterthought",
    ],
    faqs: [
      { q: "Have you built financial products that handle real money?", a: "Yes — Digistate is a live investment platform we built with real-time trading, portfolio tracking, and a custom exchange, backed by a dedicated QA team." },
      { q: "How do you approach security for fintech products?", a: "Encryption at rest and in transit, least-privilege access controls, dependency auditing, and structured code review are standard on every financial build — not optional extras." },
      { q: "Can you help with regulatory/compliance requirements?", a: "We build the workflows compliance teams need (KYC, audit logging, transaction reporting) and work alongside your legal/compliance advisors to implement their specific requirements correctly." },
      { q: "Do you support blockchain-based financial products?", a: "Yes — we've shipped tokenized assets, on-chain wallets, and smart-contract-based settlement alongside traditional financial infrastructure." },
    ],
    projectIds: [1],
  },
  {
    slug: "logistics",
    href: ROUTE.logistics_industry,
    name: "Logistics",
    icon: "feather-package",
    accent: "245,158,11",
    heroImage: "/app_images/industries/logistics.webp",
    eyebrow: "Logistics & Supply Chain",
    heroTitle: "Keep freight, fleets, and riders moving in real time",
    heroDesc:
      "We build the tracking, dispatch, and rider-matching systems that turn logistics chaos into a smooth, visible, on-time operation.",
    stats: [
      { value: "1", label: "Live logistics platform shipped" },
      { value: "Real-time", label: "GPS tracking at scale" },
      { value: "iOS & Android", label: "Native driver apps" },
    ],
    challenges: [
      { title: "No real-time visibility into shipments", desc: "Customers and dispatchers are left guessing where a shipment or rider actually is." },
      { title: "Manual dispatch and route planning", desc: "Assigning drivers and optimizing routes by hand wastes time and fuel." },
      { title: "Disconnected freight and passenger workflows", desc: "Cargo and ride-hailing operations often run on separate, poorly integrated systems." },
    ],
    capabilities: [
      { title: "Live GPS tracking", desc: "Real-time location for every shipment, vehicle, and rider on a live map." },
      { title: "Driver & fleet apps", desc: "Native mobile apps for drivers to accept, navigate, and complete jobs." },
      { title: "Dispatch & route optimization", desc: "Smart matching and routing engines that cut delivery time and cost." },
      { title: "Freight & cargo booking", desc: "End-to-end booking, tracking, and proof-of-delivery for heavy-duty shipments." },
      { title: "Customer-facing tracking portals", desc: "Branded tracking pages that keep customers informed without a support call." },
      { title: "Push notifications & alerts", desc: "Real-time status updates delivered the moment something changes." },
    ],
    whyPoints: [
      "Built Lodapoint — a live logistics and ride-hailing platform, from concept to launch",
      "Real-time systems expertise: WebSockets, live maps, push notifications",
      "Native driver and passenger apps for iOS and Android",
      "Route-matching and dispatch logic tuned for real-world traffic conditions",
      "Platforms built to scale from a handful of drivers to a full metro fleet",
    ],
    faqs: [
      { q: "Can you build a real-time tracking system for our fleet?", a: "Yes — we built Lodapoint's live GPS tracking system from scratch, giving dispatchers and customers a real-time view of every vehicle and shipment." },
      { q: "Do you build both driver-facing and customer-facing apps?", a: "We typically deliver a full ecosystem — driver app, customer app, and an admin dashboard for dispatch — all connected to the same real-time backend." },
      { q: "Can your platform handle both freight and ride-hailing?", a: "Yes — Lodapoint was built to support both cargo shipments and passenger rides on one platform, with a network of verified drivers serving either need." },
      { q: "How do you handle offline or low-connectivity areas?", a: "We design mobile apps with offline-first data handling and graceful sync, so drivers in low-signal areas can keep working without losing job data." },
    ],
    projectIds: [3],
  },
  {
    slug: "education",
    href: ROUTE.education_industry,
    name: "Education",
    icon: "feather-book-open",
    accent: "236,72,153",
    heroImage: "/app_images/industries/education.webp",
    eyebrow: "EdTech & Learning",
    heroTitle: "Learning software that keeps students coming back",
    heroDesc:
      "We design course, quiz, and progress-tracking apps engineered around one goal: daily engagement that actually sticks.",
    stats: [
      { value: "2", label: "EdTech platforms shipped" },
      { value: "Offline-first", label: "Mobile learning support" },
      { value: "1000s", label: "Of students reached" },
    ],
    challenges: [
      { title: "Low completion rates", desc: "Most learning apps lose the majority of users before they finish a single course." },
      { title: "Content that doesn't adapt to the learner", desc: "One-size-fits-all courseware ignores different paces, devices, and connectivity." },
      { title: "Disconnected instructor and student tools", desc: "Instructors and learners often work in separate, poorly synced systems." },
    ],
    capabilities: [
      { title: "Course & curriculum platforms", desc: "Structured, trackable learning paths with rich media support." },
      { title: "Quizzes & assessments", desc: "Auto-graded quizzes, progress checkpoints, and completion certificates." },
      { title: "Offline-first mobile learning", desc: "Course content that keeps working without a stable connection." },
      { title: "Instructor & classroom tools", desc: "Class management, live sessions, and student progress dashboards." },
      { title: "Community & discussion features", desc: "Peer discussion and mentorship built into the learning flow." },
      { title: "Analytics & engagement tracking", desc: "See exactly where learners drop off and why." },
    ],
    whyPoints: [
      "Shipped a discipleship/learning platform used by thousands of students",
      "Offline-first mobile architecture for learners with unreliable connectivity",
      "Course, quiz, and progress-tracking systems built from experience, not guesswork",
      "Cross-platform delivery — one codebase, native iOS and Android performance",
      "We design for completion rates, not just course uploads",
    ],
    faqs: [
      { q: "Can you build an app that works offline for students with limited connectivity?", a: "Yes — our DTS app was built offline-first specifically for this reason, syncing progress automatically once a connection is available again." },
      { q: "Do you build both the learner app and the admin/instructor tools?", a: "Yes — we typically deliver the full stack: student-facing mobile app, instructor dashboard, and a content-management admin suite." },
      { q: "Can you integrate quizzes, certificates, and progress tracking?", a: "These are core to nearly every EdTech build we do — auto-graded quizzes, milestone tracking, and completion certificates are standard features, not add-ons." },
      { q: "How do you keep students engaged over time?", a: "We design around habit-forming mechanics — streaks, progress visualization, and timely notifications — validated by what actually kept users returning on our own EdTech builds." },
    ],
    projectIds: [7, 10],
  },
  {
    slug: "healthcare",
    href: ROUTE.healthcare_industry,
    name: "Healthcare",
    icon: "feather-heart",
    accent: "34,197,148",
    heroImage: "/app_images/industries/healthcare.webp",
    eyebrow: "Digital Health",
    heroTitle: "Patient-first software, built with clinical realities in mind",
    heroDesc:
      "Telehealth, patient portals, and remote monitoring tools designed to reduce friction for patients and staff alike — without cutting corners on data protection.",
    stats: [
      { value: "24/7", label: "Support-ready builds" },
      { value: "Encrypted", label: "By default, every build" },
      { value: "Multi-role", label: "Patient, provider & admin access" },
    ],
    challenges: [
      { title: "Sensitive data that demands airtight security", desc: "Patient health information carries legal and ethical weight most software doesn't have to bear." },
      { title: "Fragmented care coordination", desc: "Patient history, appointments, and prescriptions often live across disconnected systems." },
      { title: "Low digital literacy across patient populations", desc: "Healthcare software has to work for every patient, not just the tech-comfortable ones." },
    ],
    capabilities: [
      { title: "Telehealth & virtual visits", desc: "Secure video consultations with integrated scheduling and notes." },
      { title: "Patient portals", desc: "Appointment booking, records access, and secure messaging in one place." },
      { title: "Remote monitoring", desc: "Wearable and device data streamed to care teams in near real time." },
      { title: "e-Prescriptions & pharmacy integration", desc: "Digital prescribing flows connected to pharmacy systems." },
      { title: "EMR/EHR-friendly architecture", desc: "Systems designed to integrate with, not fight, existing medical records." },
      { title: "Care team dashboards", desc: "A unified view of patient status for clinicians and admin staff." },
    ],
    whyPoints: [
      "Security and data-protection built into the architecture from day one, not retrofitted",
      "Experience designing for multiple user roles: patient, clinician, and admin",
      "Mobile-first delivery so care follows patients outside the clinic",
      "Careful, accessible UX for non-technical patient populations",
      "Long-term support built around uptime, not just launch day",
    ],
    faqs: [
      { q: "How do you handle sensitive patient data?", a: "Encryption at rest and in transit, strict access controls, and detailed audit logging are standard on every healthcare build — data protection is designed in from the architecture stage." },
      { q: "Can you build telehealth video consultation features?", a: "Yes — we integrate secure video infrastructure with scheduling, notes, and follow-up workflows so virtual visits feel as complete as in-person ones." },
      { q: "Do you build for both patients and clinical staff?", a: "We design multi-role systems as standard — patient-facing apps, clinician dashboards, and admin tools that all share one secure backend." },
      { q: "Can you integrate with wearables or remote monitoring devices?", a: "Yes — we build ingestion pipelines for wearable and device data, surfaced to care teams as actionable, near-real-time dashboards." },
    ],
    projectIds: [],
  },
  {
    slug: "ecommerce",
    href: ROUTE.ecommerce_industry,
    name: "Ecommerce",
    icon: "feather-shopping-cart",
    accent: "99,102,241",
    heroImage: "/app_images/industries/ecommerce.webp",
    eyebrow: "Ecommerce & Retail Tech",
    heroTitle: "Storefronts and commerce systems built to convert",
    heroDesc:
      "From custom storefronts to inventory, checkout, and marketplace platforms — we build commerce software that gets from browse to buy without friction.",
    stats: [
      { value: "Custom", label: "Storefronts & marketplaces" },
      { value: "Secure", label: "Checkout & payment flows" },
      { value: "Real-time", label: "Inventory sync" },
    ],
    challenges: [
      { title: "Cart abandonment at checkout", desc: "Slow, clunky checkout flows lose sales at the exact moment of intent." },
      { title: "Inventory that doesn't match reality", desc: "Out-of-sync stock levels lead to overselling and refunds." },
      { title: "Generic platforms that can't flex", desc: "Off-the-shelf ecommerce tools hit a ceiling the moment your business gets specific." },
    ],
    capabilities: [
      { title: "Custom storefronts", desc: "Fast, on-brand shopping experiences built for your catalog, not a template." },
      { title: "Marketplace platforms", desc: "Multi-vendor marketplaces with seller onboarding and payouts." },
      { title: "Checkout & payments", desc: "Streamlined, secure checkout across cards, wallets, and local payment rails." },
      { title: "Inventory & order management", desc: "Real-time stock sync across channels and warehouses." },
      { title: "Loyalty & subscriptions", desc: "Recurring revenue and retention mechanics built into the product." },
      { title: "Merchant analytics dashboards", desc: "Sales, conversion, and inventory insight in one view." },
    ],
    whyPoints: [
      "We build commerce systems as products, not template installs",
      "Full-stack delivery: storefront, checkout, inventory, and admin in one connected system",
      "Experience with multi-currency and multi-region payment flows",
      "Mobile-first shopping experiences designed for real conversion behavior",
      "Built to scale from first sale to high-volume without a re-platform",
    ],
    faqs: [
      { q: "Can you build a custom storefront instead of using Shopify/WooCommerce?", a: "Yes — we build fully custom commerce platforms when off-the-shelf tools can't match your catalog complexity, brand experience, or growth plans." },
      { q: "Do you build multi-vendor marketplace platforms?", a: "We do — including seller onboarding, commission handling, and payout logic for multi-vendor marketplaces." },
      { q: "How do you keep inventory accurate across channels?", a: "We design real-time inventory sync so stock levels update instantly across your storefront, app, and any connected sales channels." },
      { q: "Can you integrate local/regional payment methods?", a: "Yes — we regularly integrate region-specific payment rails alongside standard card processing, tailored to where your customers actually are." },
    ],
    projectIds: [],
  },
  {
    slug: "b2b-software",
    href: ROUTE.b2b_software_industry,
    name: "B2B Software",
    icon: "feather-server",
    accent: "20,184,166",
    heroImage: "/app_images/industries/b2b-software.webp",
    eyebrow: "Enterprise & B2B Platforms",
    heroTitle: "Internal tools and B2B platforms that teams actually want to use",
    heroDesc:
      "We build the dashboards, admin suites, and internal platforms that businesses run their operations on — fast, reliable, and built around real workflows.",
    stats: [
      { value: "255+", label: "Designers & developers" },
      { value: "Admin suites", label: "Shipped across every project" },
      { value: "SSO-ready", label: "Enterprise access control" },
    ],
    challenges: [
      { title: "Internal tools nobody wants to open", desc: "Clunky internal software slows teams down instead of speeding them up." },
      { title: "Disconnected departments and data", desc: "Sales, ops, and finance often work off different, unsynced sources of truth." },
      { title: "Access control that's an afterthought", desc: "Role-based permissions get bolted on late instead of designed in from the start." },
    ],
    capabilities: [
      { title: "Admin & operations dashboards", desc: "Purpose-built internal tools that match how your team actually works." },
      { title: "Workflow automation", desc: "Automate the repetitive approval and hand-off steps slowing teams down." },
      { title: "Role-based access control", desc: "Fine-grained permissions across teams, departments, and partners." },
      { title: "API & systems integration", desc: "Connect your internal tools to the third-party systems you already rely on." },
      { title: "Reporting & analytics", desc: "Custom reporting built around the metrics your business actually tracks." },
      { title: "Partner & client portals", desc: "Secure, branded portals for external stakeholders to self-serve." },
    ],
    whyPoints: [
      "Every consumer product we ship comes with a battle-tested admin suite",
      "255+ designers and developers with enterprise delivery experience",
      "We design internal tools with the same UX rigor as customer-facing products",
      "Integration-heavy work is routine for us, not a specialty add-on",
      "Built for teams that need to move fast without breaking access control",
    ],
    faqs: [
      { q: "Do you build internal tools, not just customer-facing apps?", a: "Yes — every major project we deliver includes a full admin suite, and we regularly build standalone internal tools and B2B platforms outside of that too." },
      { q: "Can you integrate with our existing enterprise systems?", a: "We build API integrations into existing CRMs, ERPs, and internal systems as a standard part of B2B engagements." },
      { q: "How do you handle role-based permissions?", a: "We design granular, role-based access control from the architecture stage so departments and partners only see what they should." },
      { q: "Can you modernize a legacy internal system?", a: "Yes — we regularly re-platform legacy internal tools, prioritizing zero-disruption migration for teams that depend on them daily." },
    ],
    projectIds: [],
  },
  {
    slug: "crm-development",
    href: ROUTE.crm_industry,
    name: "CRM Development",
    icon: "feather-users",
    accent: "251,146,60",
    heroImage: "/app_images/industries/crm.webp",
    eyebrow: "Custom CRM Development",
    heroTitle: "CRM software shaped around your sales process, not the other way around",
    heroDesc:
      "When off-the-shelf CRMs force your team to adapt to their workflow, we build one that adapts to yours — pipeline, automation, and reporting included.",
    stats: [
      { value: "Custom", label: "Pipelines & sales stages" },
      { value: "Automated", label: "Follow-ups & lead routing" },
      { value: "Unified", label: "Sales, support & marketing data" },
    ],
    challenges: [
      { title: "Generic CRMs that don't fit your process", desc: "Off-the-shelf tools force teams into someone else's idea of a sales pipeline." },
      { title: "Leads falling through the cracks", desc: "Manual follow-up tracking means opportunities get missed." },
      { title: "Sales data disconnected from support and marketing", desc: "Customer context gets lost moving between teams and tools." },
    ],
    capabilities: [
      { title: "Custom pipeline & deal tracking", desc: "Sales stages and fields that match exactly how your team sells." },
      { title: "Lead capture & routing", desc: "Automatic lead assignment based on your own rules, not a rigid template." },
      { title: "Automated follow-ups & reminders", desc: "Never let a warm lead go cold from a missed touchpoint." },
      { title: "Sales & pipeline reporting", desc: "Forecasting and performance dashboards built around your KPIs." },
      { title: "Support & ticketing integration", desc: "Customer history and support context in the same record as the deal." },
      { title: "Marketing & email integration", desc: "Campaign performance tied directly back to pipeline outcomes." },
    ],
    whyPoints: [
      "We've built CRM features into nearly every platform we ship, not just standalone CRMs",
      "Deep experience integrating sales, support, and marketing data into one view",
      "Automation-first approach — we look for what can be systematized, not just tracked",
      "Custom-built means no fighting a generic tool's limitations",
      "Reporting designed around your actual sales KPIs, not a vendor's defaults",
    ],
    faqs: [
      { q: "Why build a custom CRM instead of using Salesforce or HubSpot?", a: "When your sales process, industry rules, or integration needs outgrow what an off-the-shelf CRM can flex to, a custom build removes those ceilings entirely." },
      { q: "Can you migrate our data from an existing CRM?", a: "Yes — we handle full data migration and validation so your historical pipeline and customer data carries over cleanly." },
      { q: "Do you build lead-routing and automation logic?", a: "This is core to nearly every CRM build — automatic lead assignment, follow-up reminders, and stage-based triggers are standard." },
      { q: "Can the CRM integrate with our support and marketing tools?", a: "We regularly connect CRM data with support ticketing and marketing/email platforms so every team works from the same customer context." },
    ],
    projectIds: [],
  },
  {
    slug: "automotive",
    href: ROUTE.automotive_industry,
    name: "Automotive",
    icon: "feather-truck",
    accent: "185,102,231",
    heroImage: "/app_images/industries/automotive.webp",
    eyebrow: "Automotive & Mobility Tech",
    heroTitle: "Software for dealerships, fleets, and connected vehicles",
    heroDesc:
      "We build the dealer portals, fleet management tools, and connected-vehicle apps that modern automotive businesses run their operations on.",
    stats: [
      { value: "Fleet-ready", label: "Tracking & telematics" },
      { value: "Dealer & customer", label: "Dual-facing platforms" },
      { value: "Real-time", label: "Vehicle data sync" },
    ],
    challenges: [
      { title: "Dealer operations stuck on legacy tools", desc: "Inventory, CRM, and service scheduling often run on outdated, disconnected systems." },
      { title: "Fleet visibility gaps", desc: "Fleet managers lack real-time insight into vehicle location, health, and utilization." },
      { title: "Disconnected customer experience", desc: "Buyers and service customers get a fragmented digital experience across touchpoints." },
    ],
    capabilities: [
      { title: "Dealer inventory & CRM portals", desc: "Unified inventory, leads, and customer management for dealerships." },
      { title: "Fleet management & telematics", desc: "Real-time vehicle tracking, utilization, and maintenance alerts." },
      { title: "Service scheduling apps", desc: "Online booking and status tracking for vehicle service and repairs." },
      { title: "Connected vehicle apps", desc: "Companion apps for vehicle data, remote features, and diagnostics." },
      { title: "Dealer-to-customer marketplaces", desc: "Digital storefronts for vehicle listings, financing, and trade-ins." },
      { title: "Parts & inventory tracking", desc: "Real-time stock visibility across parts and service departments." },
    ],
    whyPoints: [
      "Real-time data systems experience directly transferable to telematics and fleet tracking",
      "We design dual-sided platforms — dealer/fleet operators and end customers — as standard",
      "Native mobile delivery for driver- and technician-facing tools",
      "Integration experience with mapping, geolocation, and IoT data streams",
      "Built to handle the operational complexity of multi-location dealer networks",
    ],
    faqs: [
      { q: "Can you build fleet tracking and telematics software?", a: "Yes — our real-time GPS and live-data systems work (built for logistics platforms) translate directly into fleet tracking, utilization, and maintenance-alert software." },
      { q: "Do you build software for dealerships specifically?", a: "We build dealer inventory, CRM, and service-scheduling portals tailored to how dealership operations actually run, not generic business software." },
      { q: "Can you integrate with vehicle telematics/IoT devices?", a: "Yes — we build ingestion and processing pipelines for vehicle sensor and telematics data, surfaced as actionable dashboards." },
      { q: "Do you build customer-facing apps for vehicle owners?", a: "We do — companion apps for service booking, vehicle status, and connected-vehicle features are a natural extension of our automotive work." },
    ],
    projectIds: [],
  },
  {
    slug: "travel",
    href: ROUTE.travel_industry,
    name: "Travel",
    icon: "feather-compass",
    accent: "14,165,233",
    heroImage: "/app_images/industries/travel.webp",
    eyebrow: "Travel & Hospitality Tech",
    heroTitle: "Booking and itinerary software built for how people actually travel",
    heroDesc:
      "From booking engines to itinerary planners and loyalty programs, we build travel software that removes friction from every step of the journey.",
    stats: [
      { value: "Multi-platform", label: "Web, iOS & Android" },
      { value: "Real-time", label: "Availability & pricing sync" },
      { value: "Global-ready", label: "Multi-currency support" },
    ],
    challenges: [
      { title: "Booking flows that lose customers", desc: "Complex, slow booking journeys drive travelers to abandon before completing a reservation." },
      { title: "Inventory and pricing that go stale", desc: "Outdated availability or pricing data erodes trust fast in travel." },
      { title: "Disconnected pre- and post-trip experience", desc: "Booking, itinerary, and support tools often don't talk to each other." },
    ],
    capabilities: [
      { title: "Booking & reservation engines", desc: "Fast, reliable booking flows across flights, stays, and experiences." },
      { title: "Itinerary & trip planning apps", desc: "Personalized trip planning that keeps travelers organized end-to-end." },
      { title: "Loyalty & rewards programs", desc: "Points, tiers, and perks that keep travelers coming back." },
      { title: "Real-time pricing & availability", desc: "Live sync with suppliers so what customers see is what they get." },
      { title: "In-trip support & notifications", desc: "Real-time alerts for delays, gate changes, and itinerary updates." },
      { title: "Partner & supplier integrations", desc: "Connect airlines, hotels, and local operators into one platform." },
    ],
    whyPoints: [
      "Real-time data sync expertise directly applicable to live pricing and availability",
      "Mobile-first design for the on-the-go nature of travel software",
      "Experience building multi-currency, multi-region digital products",
      "Push notification and live-update systems built into our core stack",
      "We design booking flows around conversion, not just feature completeness",
    ],
    faqs: [
      { q: "Can you build a booking engine with real-time availability?", a: "Yes — real-time data synchronization is one of our core strengths, essential for keeping pricing and availability accurate in a booking flow." },
      { q: "Do you build itinerary or trip-planning apps?", a: "We do — personalized, organized trip-planning apps with notifications and in-trip support are a natural fit for our mobile-first approach." },
      { q: "Can you integrate with airline, hotel, or GDS systems?", a: "We regularly integrate third-party travel APIs and supplier systems, handling the complexity so your platform presents one clean experience." },
      { q: "Do you support multi-currency and multi-region travelers?", a: "Yes — we design for global-ready travel products from the start, including currency, localization, and regional payment support." },
    ],
    projectIds: [],
  },
  {
    slug: "fashion-and-apparel",
    href: ROUTE.fashion_industry,
    name: "Fashion and Apparel",
    icon: "feather-tag",
    accent: "236,72,153",
    heroImage: "/app_images/industries/fashion.webp",
    eyebrow: "Fashion & Apparel Tech",
    heroTitle: "Retail software as considered as the collections it sells",
    heroDesc:
      "We build fashion ecommerce, virtual try-on, and inventory tools that match the visual standard your brand has already set.",
    stats: [
      { value: "Visual-first", label: "Storefront design" },
      { value: "Size & fit", label: "Smart recommendation tools" },
      { value: "Omnichannel", label: "Inventory sync" },
    ],
    challenges: [
      { title: "Generic storefronts that undersell the brand", desc: "Template ecommerce platforms rarely do justice to a fashion brand's visual identity." },
      { title: "High return rates from sizing uncertainty", desc: "Without good fit guidance, online apparel shopping drives costly returns." },
      { title: "Inventory spread across channels", desc: "In-store, online, and marketplace stock rarely stays in sync in real time." },
    ],
    capabilities: [
      { title: "Custom fashion storefronts", desc: "Visually rich shopping experiences designed around your collections." },
      { title: "Size & fit recommendation tools", desc: "Smarter sizing guidance that reduces returns and boosts confidence." },
      { title: "Virtual try-on features", desc: "AR and visualization tools that let shoppers preview before buying." },
      { title: "Omnichannel inventory sync", desc: "Real-time stock accuracy across store, app, and marketplace." },
      { title: "Loyalty & drop notifications", desc: "Keep customers engaged around new collections and restocks." },
      { title: "Influencer & lookbook integrations", desc: "Shoppable content that connects inspiration directly to checkout." },
    ],
    whyPoints: [
      "Design-forward team — we treat visual polish as a functional requirement, not decoration",
      "Ecommerce and inventory-sync experience built for fast-moving apparel catalogs",
      "Mobile-first builds, matching how fashion audiences actually shop",
      "We design for brand distinctiveness, never a generic template feel",
      "Full-stack delivery from storefront to backend inventory and fulfillment",
    ],
    faqs: [
      { q: "Can you build a storefront that matches our brand identity closely?", a: "Design-forward, distinctive UI is central to how we work — we never ship a template feel for a brand that deserves better." },
      { q: "Do you build size/fit recommendation tools?", a: "Yes — we build sizing logic and fit-guidance tools designed to reduce return rates, a major cost driver in apparel ecommerce." },
      { q: "Can you support real-time inventory across in-store and online channels?", a: "Omnichannel inventory sync is a core capability — we keep stock accurate everywhere your customers can buy." },
      { q: "Do you build virtual try-on or AR features?", a: "We do — AR-based visualization and try-on tools are increasingly standard requests we build into fashion ecommerce platforms." },
    ],
    projectIds: [],
  },
  {
    slug: "food",
    href: ROUTE.food_industry,
    name: "Food",
    icon: "feather-thermometer",
    accent: "245,158,11",
    heroImage: "/app_images/industries/food.webp",
    eyebrow: "FoodTech & Restaurant Tech",
    heroTitle: "Ordering, delivery, and kitchen software that keeps pace with service",
    heroDesc:
      "We build POS, ordering, and delivery-tracking systems for restaurants and food businesses that can't afford software slowing down service.",
    stats: [
      { value: "Real-time", label: "Order & kitchen sync" },
      { value: "Multi-location", label: "Menu & inventory management" },
      { value: "Live", label: "Delivery tracking" },
    ],
    challenges: [
      { title: "Order and kitchen systems out of sync", desc: "Delays between order-taking and kitchen prep slow down service and frustrate customers." },
      { title: "Delivery visibility gaps", desc: "Customers and restaurants both lose track of where an order actually is." },
      { title: "Menu and inventory management across locations", desc: "Multi-location food businesses struggle to keep menus and stock consistent." },
    ],
    capabilities: [
      { title: "POS & ordering systems", desc: "Fast, reliable point-of-sale built for real service-floor conditions." },
      { title: "Delivery tracking & dispatch", desc: "Live order tracking from kitchen to doorstep." },
      { title: "Kitchen display systems", desc: "Real-time order routing that keeps kitchens running smoothly." },
      { title: "Menu & inventory management", desc: "Consistent menus and accurate stock across every location." },
      { title: "Loyalty & rewards", desc: "Repeat-visit mechanics built into the ordering experience." },
      { title: "Multi-location admin dashboards", desc: "Centralized visibility and control across your whole footprint." },
    ],
    whyPoints: [
      "Real-time systems expertise applies directly to kitchen-to-delivery order flow",
      "We understand the operational pressure food service software runs under",
      "Native mobile apps for delivery drivers and in-store staff alike",
      "Multi-location architecture designed in from day one, not retrofitted",
      "Reliable under load — built and tested for peak-hour traffic, not just demos",
    ],
    faqs: [
      { q: "Can you build a POS system integrated with online ordering?", a: "Yes — we build unified systems where in-store POS and online ordering share the same real-time inventory and kitchen queue." },
      { q: "Do you build delivery tracking for food orders?", a: "We do — live GPS tracking and status updates, built from the same real-time systems expertise behind our logistics platforms." },
      { q: "Can you support multiple restaurant locations from one system?", a: "Yes — multi-location menu, inventory, and reporting management is a standard part of our food-tech builds." },
      { q: "Will the system hold up during peak service hours?", a: "We design and load-test specifically for peak-hour traffic — food service software has zero tolerance for slowdowns at the busiest moment." },
    ],
    projectIds: [],
  },
  {
    slug: "manufacturing",
    href: ROUTE.manufacturing_industry,
    name: "Manufacturing",
    icon: "feather-settings",
    accent: "100,116,139",
    heroImage: "/app_images/industries/manufacturing.webp",
    eyebrow: "Manufacturing & Industrial Tech",
    heroTitle: "Production visibility software for the factory floor",
    heroDesc:
      "We build the monitoring, inventory, and quality-control tools that give manufacturing teams real-time visibility into production — without disrupting the line.",
    stats: [
      { value: "Real-time", label: "Production monitoring" },
      { value: "IoT-ready", label: "Sensor & device integration" },
      { value: "Quality-first", label: "QA workflow tooling" },
    ],
    challenges: [
      { title: "No real-time visibility into production", desc: "Managers often only learn about a bottleneck or defect after it's already cost time and material." },
      { title: "Manual quality control processes", desc: "Paper-based inspection and reporting slows down issue detection." },
      { title: "Disconnected inventory and production data", desc: "Raw material and output tracking rarely syncs with production in real time." },
    ],
    capabilities: [
      { title: "Production monitoring dashboards", desc: "Real-time visibility into line status, throughput, and downtime." },
      { title: "IoT & sensor data integration", desc: "Machine and sensor data streamed into actionable dashboards." },
      { title: "Quality control workflows", desc: "Digital inspection and defect-tracking that replaces paper forms." },
      { title: "Inventory & materials tracking", desc: "Real-time raw material and finished-goods visibility." },
      { title: "Maintenance scheduling", desc: "Predictive and scheduled maintenance tools that reduce downtime." },
      { title: "Reporting & compliance tools", desc: "Production and quality records ready for audit at any time." },
    ],
    whyPoints: [
      "Real-time data pipeline experience directly applicable to production monitoring",
      "We design tablet- and floor-friendly interfaces for shop-floor conditions",
      "IoT and sensor integration experience across multiple product builds",
      "Systems designed to run reliably in low-connectivity industrial environments",
      "Admin and reporting tooling built for operational, not just executive, use",
    ],
    faqs: [
      { q: "Can you integrate with our existing factory sensors/IoT devices?", a: "Yes — we build ingestion pipelines for sensor and machine data, turned into real-time dashboards your team can actually act on." },
      { q: "Do you build software usable directly on the shop floor?", a: "We design tablet- and floor-friendly interfaces built for the realities of industrial environments, not just office use." },
      { q: "Can the system work with unreliable factory-floor connectivity?", a: "We build offline-tolerant, sync-on-reconnect systems for exactly this kind of environment." },
      { q: "Do you build quality control and inspection tools?", a: "Yes — digital inspection workflows and defect tracking are a common request we build to replace slow, error-prone paper processes." },
    ],
    projectIds: [],
  },
  {
    slug: "legal",
    href: ROUTE.legal_industry,
    name: "Legal",
    icon: "feather-file-text",
    accent: "71,85,105",
    heroImage: "/app_images/industries/legal.webp",
    eyebrow: "LegalTech",
    heroTitle: "Practice management software built around confidentiality and precision",
    heroDesc:
      "We build case management, document, and client-portal software for legal teams who need airtight security and zero tolerance for error.",
    stats: [
      { value: "Encrypted", label: "Document handling by default" },
      { value: "Role-based", label: "Access & audit trails" },
      { value: "Client portals", label: "Secure, self-service access" },
    ],
    challenges: [
      { title: "Confidential documents scattered across tools", desc: "Case files and client communication often live across email, drives, and disconnected systems." },
      { title: "Manual, error-prone case tracking", desc: "Deadlines and case status tracked by hand introduce risk that's costly in legal work." },
      { title: "Clients left without visibility", desc: "Clients frequently have no self-service way to check case status or documents." },
    ],
    capabilities: [
      { title: "Case & matter management", desc: "Centralized case tracking, deadlines, and task assignment." },
      { title: "Secure document management", desc: "Encrypted storage, version control, and access logging for case files." },
      { title: "Client portals", desc: "Secure, self-service access to case status and shared documents." },
      { title: "e-Signing & contract workflows", desc: "Digital signing flows for agreements and filings." },
      { title: "Billing & time tracking", desc: "Accurate, auditable billing tied directly to logged case work." },
      { title: "Compliance & audit trails", desc: "Full activity logging for every document and case action." },
    ],
    whyPoints: [
      "Security and access-control discipline carried over from our fintech and healthcare work",
      "We design for confidentiality as a default requirement, not a configuration option",
      "Client-portal experience built for clarity, reducing routine status-check calls",
      "Document workflows built around version control and audit trails",
      "Long-term support relationships — legal software has to keep working, quietly, for years",
    ],
    faqs: [
      { q: "How do you protect confidential legal documents?", a: "Encryption, strict role-based access, and detailed audit logging are standard on every legal-tech build we deliver." },
      { q: "Can you build a self-service client portal?", a: "Yes — secure client portals for case status and document sharing are one of the most common legal-tech requests we fulfill." },
      { q: "Do you build billing and time-tracking tools?", a: "We do — accurate, auditable time and billing tracking tied directly to logged case activity is a standard module." },
      { q: "Can you integrate e-signing into our workflows?", a: "Yes — we build e-signing directly into document and contract workflows so agreements move without leaving the platform." },
    ],
    projectIds: [],
  },
  {
    slug: "agriculture",
    href: ROUTE.agriculture_industry,
    name: "Agriculture",
    icon: "feather-sun",
    accent: "34,197,94",
    heroImage: "/app_images/industries/agriculture.webp",
    eyebrow: "AgriTech",
    heroTitle: "Farm and supply-chain software built for real field conditions",
    heroDesc:
      "We build monitoring, marketplace, and supply-chain tools for agriculture — designed to work reliably where connectivity can't be guaranteed.",
    stats: [
      { value: "Offline-first", label: "Field-ready mobile apps" },
      { value: "Farm-to-market", label: "Supply chain visibility" },
      { value: "IoT-ready", label: "Sensor & yield data" },
    ],
    challenges: [
      { title: "Unreliable connectivity in the field", desc: "Most farm-management software assumes a stable connection that rural areas simply don't have." },
      { title: "Disconnected farm-to-market supply chains", desc: "Produce, pricing, and logistics data rarely connect smoothly from farm to buyer." },
      { title: "Manual yield and resource tracking", desc: "Paper-based record-keeping leaves farm data underused and hard to act on." },
    ],
    capabilities: [
      { title: "Farm & field monitoring apps", desc: "Track yield, resources, and field activity from a mobile device." },
      { title: "Offline-first mobile architecture", desc: "Full functionality without a live connection, syncing when back online." },
      { title: "Agri-marketplaces", desc: "Connect farmers directly with buyers, cutting out inefficient middle steps." },
      { title: "Supply chain & logistics tracking", desc: "Farm-to-market visibility across the whole supply chain." },
      { title: "Sensor & IoT data integration", desc: "Soil, weather, and equipment data turned into actionable insight." },
      { title: "Cooperative & resource management", desc: "Shared-resource and cooperative coordination tools." },
    ],
    whyPoints: [
      "Offline-first mobile architecture is a specialty, not a bolt-on — proven on live products",
      "Real-time logistics and supply-chain systems experience transfers directly to farm-to-market tracking",
      "We design for low-bandwidth, low-connectivity realities from day one",
      "Marketplace-building experience across multiple industries",
      "Practical, field-tested UX — not just a polished demo that breaks outside the office",
    ],
    faqs: [
      { q: "Will the app work without reliable internet in rural areas?", a: "Yes — offline-first mobile design is one of our core strengths, built specifically for exactly this kind of connectivity gap." },
      { q: "Can you build a marketplace connecting farmers and buyers?", a: "We can — our marketplace and logistics experience applies directly to farm-to-market platforms that cut out inefficient middle steps." },
      { q: "Do you integrate with agricultural IoT sensors?", a: "Yes — we build data pipelines for soil, weather, and equipment sensors, surfaced as usable, actionable dashboards." },
      { q: "Can you track produce through the whole supply chain?", a: "Farm-to-market supply chain visibility draws directly on our real-time logistics tracking experience from other builds." },
    ],
    projectIds: [],
  },
  {
    slug: "hospitality",
    href: ROUTE.hospitality_industry,
    name: "Hospitality",
    icon: "feather-star",
    accent: "20,184,166",
    heroImage: "/app_images/industries/hospitality.webp",
    eyebrow: "Hospitality & Guest Tech",
    heroTitle: "Guest experience software that turns stays into loyalty",
    heroDesc:
      "We build booking, guest-services, and loyalty platforms that make every stay feel effortless — for guests and for your front-desk team.",
    stats: [
      { value: "Direct", label: "Booking & reservation flows" },
      { value: "Digital", label: "Guest check-in & keys" },
      { value: "Loyalty-ready", label: "Repeat-guest programs" },
    ],
    challenges: [
      { title: "Over-reliance on third-party booking platforms", desc: "High commission fees eat into margins when direct booking isn't a strong option." },
      { title: "Slow, manual guest service requests", desc: "Guests waiting on calls or front-desk visits for simple requests hurts the experience." },
      { title: "Guest data that never becomes loyalty", desc: "Stay history rarely gets used to build repeat business." },
    ],
    capabilities: [
      { title: "Direct booking engines", desc: "Reduce commission costs with a fast, reliable booking flow you control." },
      { title: "Digital check-in & keyless entry", desc: "Guest self-service that reduces front-desk bottlenecks." },
      { title: "Guest services & request apps", desc: "In-stay requests and concierge service from a guest's phone." },
      { title: "Loyalty & rewards programs", desc: "Turn stay history into repeat bookings with a real loyalty system." },
      { title: "Property & staff management", desc: "Housekeeping, maintenance, and staff coordination tools." },
      { title: "Review & reputation tools", desc: "Streamlined feedback collection tied to service recovery workflows." },
    ],
    whyPoints: [
      "Booking and reservation-flow experience built for conversion, not just function",
      "Mobile-first guest experiences designed around real travel behavior",
      "Loyalty and rewards mechanics built into products across multiple industries",
      "Systems designed to reduce front-desk load, not add another dashboard to manage",
      "Support built around your operating hours — hospitality never really closes",
    ],
    faqs: [
      { q: "Can you build a direct booking engine to reduce OTA commissions?", a: "Yes — a fast, trustworthy direct booking flow is one of the highest-leverage builds we do for hospitality clients." },
      { q: "Do you build digital check-in or keyless entry features?", a: "We do — guest self-service check-in and digital key integration are increasingly standard requests we build into hospitality platforms." },
      { q: "Can you build a loyalty program into our booking platform?", a: "Yes — points, tiers, and rewards logic tied directly to booking and stay history is a common module we deliver." },
      { q: "Do you build tools for staff, not just guests?", a: "We do — housekeeping, maintenance, and front-desk coordination tools are part of a complete hospitality platform, not an afterthought." },
    ],
    projectIds: [],
  },
];

export const getIndustryBySlug = (slug) => INDUSTRIES.find((i) => i.slug === slug);
